config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index,:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update,:destroy,:show] do
    resources :messages, only: [:index, :create ]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
      
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader

  # def self.create_photos_by(photo_params)

  #   # /* そもそも一枚も上がってきてない時のためのvalidate */
  #     return false if photo_params[:content].nil?
    
  #   # /* 途中でエラった時にRollbackするようにTransaction */
  #     Photo.transaction do 
    
  #   # /* アップロードされた画像を一枚ずつ処理 */
  #       message_params[:content].each do |photo|
  #         new_photo = Message.new(title: message_params[:image], content: photo)
  #         return false unless new_photo.save!
  #       end
  #     end
    
  #     true
  #   end
    

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages

  has_many :messages, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_message_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_message_idよりも新しい(大きい)メッセージ達のみを取得
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.includes(:users).order("created_at DESC")
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  def show
    @group = Group.find(params[:id])
    @group = group_messages_path([:group_id])
    # @group = @group.messages
    
    
    
  end

  def destroy
    # group = Group.find(params[:id])
    # group = destroy
    # redirest_to root_path

    @group = Group.find(params[:id])
    @group = destroy(group_params[:id])
    redirect_to @group, notice: 'グループを削除しました'
    
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      # redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
    # else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  def edit
  end


  def destroy
    group = Group.find(params[:id])
    group.destroy
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
    # params.require(:message).permit( :content, {image: []}).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users/registrations_controller.rb
# protected
 
#   def configure_account_update_params
#     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar, :avatar_cache, :remove_avatar])
#   end

#   def after_update_path_for(resource)
#     account_page_path
#   end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  def show
    @group = Group.find(params[:id])
    @group = @group.users
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right

      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

        - group.users.each do |user|
          - if current_user.name != user.name
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.name 
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'
      = link_to "削除する", :back, class: 'btn',data: {confirm:"本当によろしいですか??"}
      -# = link_to "削除する", destroy_user_session_path, method: :delete, data: {confirm:"本当によろしいですか??"}

app/views/groups/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title "chat-spac2e"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{:src => "intense.min.js", :type => "text/javascript"}
    :css
    .fullscreen-image
    :javascript
      var elements = document.querySelectorAll( '.fullscreen-image' );
      Intense( elements );


  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.message{data: {message: {id: message.id}}}
  .upper-message
    .upper-message__user-name
      = message.user.name
    .upper-message__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
      
.scroll
  %span.lower-message
    - if message.content.present?
      %p.lower-message__content
        = message.content

  // いいねボタンの機能
.btn_1
  %button#up イイね!👍❤️
  #disp_count 0
  %button#down ↓

= image_tag message.image.url, class: 'lower-message__image' if message.image.present?

%ul.more_list
  %li.botn
    = link_to '詳細', "/messages/#{message.id}", method: :get
  - if user_signed_in? && current_user.id == message.user_id
    %li.botn
      = link_to '編集', "/messages/#{message.id}/edit", method: :get
    %li.botn
      = link_to '削除', "/messages/#{message.id}", method: :delete

app/views/messages/index.html.haml
.wrapper
  = render "shared/side_bar"
  = render "shared/main_chat"

app/views/messages/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/shared/_main_chat.html.haml
%wrapper
  .form
    = form_for [@group, @message] do |f|
      = f.text_field :content, class: 'form__message', placeholder: 'NEW-Messageを入れてください!! 　　　　　　　　　　　　　　　                 写真はココ 👉'
      .form__mask
        = f.label :image, class: 'form__mask__image' do
          = icon('far', 'images', class: 'icon')
          = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'form__submit'
  .id_back-ground
    -# = image_tag("スクリーンショット 2020-02-19 2.05.19.png")
    -# = link_to current_user, group_path(current_user), class: "header"
    -# = link_to "詳細",edit_group_path(@group.id),{class:'show'}
    .messages
      = render @messages
    
    .chat-main__main-header
      .chat-main__main-header__left
        %h2.chat-main__main-header__left__into-group
          = @group.name
        %ul.chat-main__main-header__left-box
          %li.chat-main__main-header__left-box__into__meber
            Member:
          %li.chat-main__main-header__left-box__into__meber-meber 
            - @group.group_users.each do |group_user|
              = group_user.user.name
      = link_to"Edit", edit_group_path(@group.id), {class: "btn"}
      

app/views/shared/_side_bar.html.haml
%wrapper
  .chat-side
    .chat-side-header
      .chat-side-header__box
        %h1.chat-side-header__box__user 
          = current_user.name
          %ul.chat-side-header__box__icon
          %li.chat-side-header__box__icon__new-group
          = link_to new_group_path do
            =icon('fas','edit', class: 'pencil')
          %li.chat-side-header__box__icon__new-group1
          = link_to edit_user_path(current_user) do
            = icon('fas', 'cog', class: 'gea')
    .groups
      -current_user.groups.each do |group|
        .group
          = link_to group_messages_path(group) do
            %h2.group__name
              = group.name
            %h3.group__message
              = group.show_last_message
            .css-cube
              .css-face.css-forward 
              .css-face.css-reverse 
              .css-face.css-right 
              .css-face.css-left 
              .css-face.css-top 
              .css-face.css-bottom 

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'


    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'